---
version: "2.0"
services:
  mysql3306:
    image: centos/mysql-57-centos7
    ports:
      - 3306:3306
    volumes:
      - ./my.cnf:/etc/my.cnf.d/98-my.cnf
      - ./my3306.cnf:/etc/my.cnf.d/99-my.cnf
    env_file:
      - ./mysql.env
  mysql3307:
    image: centos/mysql-57-centos7
    ports:
      - 3307:3306
    volumes:
      - ./my.cnf:/etc/my.cnf.d/98-my.cnf
      - ./my3307.cnf:/etc/my.cnf.d/99-my.cnf
    env_file:
      - ./mysql.env
