---
version: "2.0"
services:
  mysql3306:
    image: centos/mysql-57-centos7
    ports:
      - 3306:3306
    volumes:
      - ./mysql_server.cnf:/etc/my.cnf.d/98-my.cnf
      - ./mysql_server_3306.cnf:/etc/my.cnf.d/99-my.cnf
    env_file:
      - ./docker-mysql.env
  mysql3307:
    image: centos/mysql-57-centos7
    ports:
      - 3307:3306
    volumes:
      - ./mysql_server.cnf:/etc/my.cnf.d/98-my.cnf
      - ./mysql_server_3307.cnf:/etc/my.cnf.d/99-my.cnf
    env_file:
      - ./docker-mysql.env
